
#O Dockerfile é um script que define como construir uma imagem Docker, que é um snapshot de um ambiente de execução completo, incluindo o sistema operacional, dependências e a sua aplicação
#AQUI BASICAMENTE ESTAMOS CRIANDO OQUE VAI FICAR DENTRO DE "FILES" NO CONTEINER DOCKER. (e oque vai ficar lá tem que ser a aplicação)

# Usar a imagem base Node.js versão mais recente
FROM node:latest

# Definir o diretório de trabalho dentro do contêiner como /app na maquina virtual
WORKDIR /app

# Copiar package.json e package-lock.json do diretório atual no host para o diretório de trabalho no contêiner
COPY package*.json ./

# Executar o comando npm install dentro do contêiner para instalar todas as dependências do projeto
RUN npm install

# Copiar o restante do código da aplicação do diretório atual no host para o diretório de trabalho no contêiner ("app")
COPY . .

# Informar ao Docker que o contêiner escutará na porta 3000 em tempo de execução
EXPOSE 3000

# Definir o comando a ser executado quando o contêiner iniciar
# Este comando geralmente inicia o servidor da aplicação conforme definido no package.json (por exemplo, "node server.js" ou "vue-cli-service serve" para uma aplicação Vue.js)
CMD ["npm", "start"]